version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/work

  # 餈質
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  # 餈質
  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 13306:3306

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=db
  #     - PMA_USER=root
  #     - PMA_PASSWORD=root
  #   ports:
  #     - 4040:80
  #   volumes:
  #     - ./docker/phpmyadmin/sessions:/sessions

volumes:
  db-store:
